[package]
name = "typetest"
version = "1.0.0"
authors = ["Jon Pacheco <jon.pacheco2@gmail.com>"]
edition = "2018"
description = "An offline typing test, written using Iced."

[dependencies]
fastrand = "1.3"

# TODO: Use next version of Iced once available
[dependencies.iced]
git = "https://github.com/hecrj/iced"
rev = "9ba4cfd23f4620bab93df9616617643604db2c79"
default-features = false
features = ["async-std", "glow"]
