[package]
name = "typetest-core"
version = "0.1.0"
authors = ["Jon Pacheco <jon.pacheco2@gmail.com>"]
edition = "2018"

[dependencies]
rand = { version = "0.7", features = ["small_rng"] }

[dev-dependencies]
rstest = "0.6"
