[package]
name = "typetest_widgets"
description = "An offline keyboard typing test."
repository = "https://github.com/Ace4896/typetest"
version = "1.1.0"
authors = ["Jon Pacheco <jon.pacheco2@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
iced_native = "0.10"
iced_style = "0.8"
